name: Build cefbrowser

on:
  workflow_dispatch:

permissions: write-all

jobs:
  arm-openssl-3:
    name: arm-openssl-3
    uses: ./.github/workflows/build-cefbrowser-docker.yml
    with:
      arch: armhf
      arch_build: arm
      compiler: arm-linux-gnueabihf
      compiler_version: 11
      ubuntu_version: 22.04
      ubuntu_name: jammy
    secrets: inherit

  arm64-openssl-3:
    name: arm64-openssl-3
    uses: ./.github/workflows/build-cefbrowser-docker.yml
    with:
      arch: arm64
      arch_build: arm64
      compiler: aarch64-linux-gnu
      compiler_version: 11
      ubuntu_version: 22.04
      ubuntu_name: jammy
    secrets: inherit

  amd64-openssl-3:
    name: amd64-openssl-3
    uses: ./.github/workflows/build-cefbrowser-docker.yml
    with:
      arch: amd64
      arch_build: amd64
      compiler: x86_64-linux-gnu
      compiler_version: 11
      ubuntu_version: 22.04
      ubuntu_name: jammy
    secrets: inherit